# generated by datamodel-codegen:
#   filename:  openapi.yaml

from enum import StrEnum

from pydantic import BaseModel, Field


class Status(StrEnum):
    ok = "ok"
    degraded = "degraded"


class Health(BaseModel):
    status: Status
    version: str = Field(..., description="Running service version")
